### PR TITLE
[Enhancement] Update kernel-url input description

### PR DESCRIPTION
**Pull request by whyakari**
Updated the description of the `kernel-url` input to specify that it accepts either a URL or a GitHub username/repo for the Android kernel source code. This provides clarity to users regarding the expected input format.

Old Description:
- URL of Android kernel source code for your phone

New Description:
- URL or username/repo (GitHub) of Android kernel source code for your phone

### CODE REVIEW

**Comment by dabao1955** [comment]
But what if I pull the Android kernel source code from a self-built git server or GitLab ?

**Comment by whyakari** [comment]
> But what if I pull the Android kernel source code from a self-built git server or GitLab ?

huh, true. so can we use something like this?
```sh
#!/bin/bash

kernel_url="${{ inputs.kernel-url }}"
git_provider="${{ inputs.git-provider }}"

if [[ $git_provider == "github" ]]; then
    git_host="github.com"
elif [[ $git_provider == "gitlab" ]]; then
    git_host="gitlab.com"
else
    # Default to GitHub if no provider specified
    git_host="github.com"
fi

git clone --recursive https://$git_host/$kernel_url -b "${{ inputs.branch }}" --depth=${{ inputs.depth }} kernel/${{ inputs.kernel-dir }}
```

**Comment by dabao1955** [comment]
> > But what if I pull the Android kernel source code from a self-built git server or GitLab ?
> 
> huh, true. so can we use something like this?
> 
> ```shell
> #!/bin/bash
> 
> kernel_url="${{ inputs.kernel-url }}"
> git_provider="${{ inputs.git-provider }}"
> 
> if [[ $git_provider == "github" ]]; then
>     git_host="github.com"
> elif [[ $git_provider == "gitlab" ]]; then
>     git_host="gitlab.com"
> else
>     # Default to GitHub if no provider specified
>     git_host="github.com"
> fi
> 
> git clone --recursive https://$git_host/$kernel_url -b "${{ inputs.branch }}" --depth=${{ inputs.depth }} kernel/${{ inputs.kernel-dir }}
> ```
> 
> where is a new input`git-provider`

Why don't I directly enter the Android kernel source code URL on github into kernel-url?

**Comment by whyakari** [comment]
> > > But what if I pull the Android kernel source code from a self-built git server or GitLab ?
> > 
> > 
> > huh, true. so can we use something like this?
> > ```shell
> > #!/bin/bash
> > 
> > kernel_url="${{ inputs.kernel-url }}"
> > git_provider="${{ inputs.git-provider }}"
> > 
> > if [[ $git_provider == "github" ]]; then
> >     git_host="github.com"
> > elif [[ $git_provider == "gitlab" ]]; then
> >     git_host="gitlab.com"
> > else
> >     # Default to GitHub if no provider specified
> >     git_host="github.com"
> > fi
> > 
> > git clone --recursive https://$git_host/$kernel_url -b "${{ inputs.branch }}" --depth=${{ inputs.depth }} kernel/${{ inputs.kernel-dir }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where is a new input`git-provider`
> 
> Why don't I directly enter the Android kernel source code URL on github into kernel-url?

less code (:

**Comment by dabao1955** [comment]
> > > > But what if I pull the Android kernel source code from a self-built git server or GitLab ?
> > > 
> > > 
> > > huh, true. so can we use something like this?
> > > ```shell
> > > #!/bin/bash
> > > 
> > > kernel_url="${{ inputs.kernel-url }}"
> > > git_provider="${{ inputs.git-provider }}"
> > > 
> > > if [[ $git_provider == "github" ]]; then
> > >     git_host="github.com"
> > > elif [[ $git_provider == "gitlab" ]]; then
> > >     git_host="gitlab.com"
> > > else
> > >     # Default to GitHub if no provider specified
> > >     git_host="github.com"
> > > fi
> > > 
> > > git clone --recursive https://$git_host/$kernel_url -b "${{ inputs.branch }}" --depth=${{ inputs.depth }} kernel/${{ inputs.kernel-dir }}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > where is a new input`git-provider`
> > 
> > 
> > Why don't I directly enter the Android kernel source code URL on github into kernel-url?
> 
> less code (:

But this will lead to unnecessary options, even though it is a rare behavior to pull the Android kernel source code from a self-built git server or other hosting platforms such as gitlab.
I previously introduced the android-ndk-x64 option to handle the problem of download link errors when the ndk version is smaller than r22, but I implemented it using regular expressions.
Regardless, it's a good idea.

**Comment by dabao1955** [comment]
And this may lead to ambiguity issues :(

**Pull request closed without merging**
