### PR TITLE
Fix patch application feedback

### PR DESCRIPTION
**Pull request by Fyg369**
## Type
- [ ] bug fix 

- [ ] feature add 

- [ ] other 

## Checkbox
- [ ] do not have break changes 

- [ ] normal operation will not be affected after modification 

## Linked issues
<!-- if want to fix it, try "fixes: #13">

### CODE REVIEW

**Comment by Fyg369** [comment]
看着更直观一点

**Comment by dabao1955** [comment]
> 看着更直观一点
> 
> 
> 

直接在最后一行写patched successfully就醒了

**Comment by Fyg369** [comment]
> > 看着更直观一点
> > 
> 
> 直接在最后一行写patched successfully就醒了

确实代码重复了

**Comment by Fyg369** [comment]
因为lxc补丁有路径问题，根据patch.sh补丁制作了lxc.sh补丁，已经在乌班图虚拟机里测试通过，大佬看下是否还有优化的地方？

#!/usr/bin/env bash

set -e

if grep -q "int cgroup_add_file" kernel/cgroup.c >/dev/null 2>&1; then
    cgroup='kernel/cgroup.c'
else
    cgroup='kernel/cgroup/cgroup.c'
fi

patch_files=(
    "$cgroup"
    net/netfilter/xt_qtaguid.c
)

for i in "${patch_files[@]}"; do

    if [[ "$i" == "$cgroup" ]]; then
        if grep -Fq "snprintf(name, CGROUP_FILE_NAME_MAX" "$i"; then
            echo "Warning: $i contains LXC"
            continue
        fi
    fi

    if [[ "$i" == "net/netfilter/xt_qtaguid.c" ]]; then
        if grep -Fq "struct rtnl_link_stats64 *stats" "$i"; then
            echo "Warning: $i contains LXC"
            continue
        fi
    fi

    case $i in

    "$cgroup")
        sed -i '/int cgroup_add_file/,/return 0;/{
        /return 0;/i\
    \tif (cft->ss && (cgrp->root->flags & CGRP_ROOT_NOPREFIX) && !(cft->flags & CFTYPE_NO_PREFIX)) {\
        \tsnprintf(name, CGROUP_FILE_NAME_MAX, "%s.%s", cft->ss->name, cft->name);\
        \tkernfs_create_link(cgrp->kn, name, kn);\
    \t}
}' "$cgroup"
        ;;

    net/netfilter/xt_qtaguid.c)
        sed -i '/int iface_stat_fmt_proc_show/,/^}/ {
    s/struct rtnl_link_stats64 dev_stats, \*stats/struct rtnl_link_stats64 \*stats/
    /if (iface_entry->active)/i\
    \tstats = &no_dev_stats;
    /if (iface_entry->active)/,+5d
}' net/netfilter/xt_qtaguid.c
        ;;
    esac

    echo "Patch applied successfully to $i"

done

**Comment by dabao1955** [comment]
> 因为lxc补丁有路径问题，根据patch.sh补丁制作了lxc.sh补丁，已经在乌班图虚拟机里测试通过，大佬看下是否还有优化的地方？如果没问题我将会第二次提交
> 
> #!/usr/bin/env bash
> 
> set -e
> 
> if grep -q "int cgroup_add_file" kernel/cgroup.c >/dev/null 2>&1; then
>     cgroup='kernel/cgroup.c'
> else
>     cgroup='kernel/cgroup/cgroup.c'
> fi
> 
> patch_files=(
>     "$cgroup"
>     net/netfilter/xt_qtaguid.c
> )
> 
> for i in "${patch_files[@]}"; do
> 
>     if [[ "$i" == "$cgroup" ]]; then
>         if grep -Fq "snprintf(name, CGROUP_FILE_NAME_MAX" "$i"; then
>             echo "Warning: $i contains LXC"
>             continue
>         fi
>     fi
> 
>     if [[ "$i" == "net/netfilter/xt_qtaguid.c" ]]; then
>         if grep -Fq "struct rtnl_link_stats64 *stats" "$i"; then
>             echo "Warning: $i contains LXC"
>             continue
>         fi
>     fi
> 
>     case $i in
> 
>     "$cgroup")
>         sed -i '/int cgroup_add_file/,/return 0;/{
>         /return 0;/i\
>     \tif (cft->ss && (cgrp->root->flags & CGRP_ROOT_NOPREFIX) && !(cft->flags & CFTYPE_NO_PREFIX)) {\
>         \tsnprintf(name, CGROUP_FILE_NAME_MAX, "%s.%s", cft->ss->name, cft->name);\
>         \tkernfs_create_link(cgrp->kn, name, kn);\
>     \t}
> }' "$cgroup"
>         ;;
> 
>     net/netfilter/xt_qtaguid.c)
>         sed -i '/int iface_stat_fmt_proc_show/,/^}/ {
>     s/struct rtnl_link_stats64 dev_stats, \*stats/struct rtnl_link_stats64 \*stats/
>     /if (iface_entry->active)/i\
>     \tstats = &no_dev_stats;
>     /if (iface_entry->active)/,+5d
> }' net/netfilter/xt_qtaguid.c
>         ;;
>     esac
> 
>     echo "Patch applied successfully to $i"
> 
> done

shellcheck过了补丁能打成功就行
还有不要删评论了

**Comment by Fyg369** [comment]
> > 因为lxc补丁有路径问题，根据patch.sh补丁制作了lxc.sh补丁，已经在乌班图虚拟机里测试通过，大佬看下是否还有优化的地方？如果没问题我将会第二次提交
> > #!/usr/bin/env bash
> > set -e
> > if grep -q "int cgroup_add_file" kernel/cgroup.c >/dev/null 2>&1; then
> > cgroup='kernel/cgroup.c'
> > else
> > cgroup='kernel/cgroup/cgroup.c'
> > fi
> > patch_files=(
> > "$cgroup"
> > net/netfilter/xt_qtaguid.c
> > )
> > for i in "${patch_files[@]}"; do
> > ```
> > if [[ "$i" == "$cgroup" ]]; then
> >     if grep -Fq "snprintf(name, CGROUP_FILE_NAME_MAX" "$i"; then
> >         echo "Warning: $i contains LXC"
> >         continue
> >     fi
> > fi
> > 
> > if [[ "$i" == "net/netfilter/xt_qtaguid.c" ]]; then
> >     if grep -Fq "struct rtnl_link_stats64 *stats" "$i"; then
> >         echo "Warning: $i contains LXC"
> >         continue
> >     fi
> > fi
> > 
> > case $i in
> > 
> > "$cgroup")
> >     sed -i '/int cgroup_add_file/,/return 0;/{
> >     /return 0;/i\
> > \tif (cft->ss && (cgrp->root->flags & CGRP_ROOT_NOPREFIX) && !(cft->flags & CFTYPE_NO_PREFIX)) {\
> >     \tsnprintf(name, CGROUP_FILE_NAME_MAX, "%s.%s", cft->ss->name, cft->name);\
> >     \tkernfs_create_link(cgrp->kn, name, kn);\
> > \t}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }' "$cgroup"
> > ;;
> > ```
> > net/netfilter/xt_qtaguid.c)
> >     sed -i '/int iface_stat_fmt_proc_show/,/^}/ {
> > s/struct rtnl_link_stats64 dev_stats, \*stats/struct rtnl_link_stats64 \*stats/
> > /if (iface_entry->active)/i\
> > \tstats = &no_dev_stats;
> > /if (iface_entry->active)/,+5d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }' net/netfilter/xt_qtaguid.c
> > ;;
> > esac
> > ```
> > echo "Patch applied successfully to $i"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > done
> 
> shellcheck过了补丁能打成功就行 还有不要删评论了

已经过了shellcheck

**Comment by Fyg369** [comment]
如果通过的话，这个提交标题可以改回第一次提交的标题

**Comment by dabao1955** [comment]
> 如果通过的话，这个提交标题可以改回第一次提交的标题

需要通过完整的ci检查

**Comment by Fyg369** [comment]
> > 如果通过的话，这个提交标题可以改回第一次提交的标题
> 
> 需要通过全面ci检查

只是在原有脚本代码基础上末尾添加了echo "Patch applied successfully to $i"

**Comment by dabao1955** [comment]
> > > 如果通过的话，这个提交标题可以改回第一次提交的标题
> > 
> > 需要通过全面ci检查
> 
> 只是在原有脚本代码基础上末尾添加了echo "Patch applied successfully to $i"

o

**Review by dabao1955 — APPROVED** [review]

**Pull request merged**
